
// Add whatever coins you will support to the list.

module.exports = {
    'kda': 'kadena',
    'btc': 'bitcoin',
    'eth': 'ethereum',
    'xrp': 'ripple',
    'doge': 'dogecoin',
    "flux": "zelcash",
    "kdx": "kaddex",
    "kdl": "kdlaunch",
    "kds": "kdswap",
    "hype": "hypercent",
    "ada": "cardano",
    "matic": "matic-network",
    "sol": "solana",
    "apt": "aptos",
    "trx": "tron",
    "avax": "avalanche-2",
    "avalanche": "avalanche-2",
    "egld": "elrond-erd-2",
    "elrond": "elrond-erd-2",
    "multiversx": "elrond-erd-2",
    "bnb": "binancecoin",
    "cake": "pancakeswap-token",
    "kas": "kaspa",
    "usdt": "tether",
    "busd": "binance-usd",
    "usdc": "usd-coin",
    "dot": "polkadot", 
  }